import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayoutHome({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>

      <h1>Home</h1>
      {children}
    </>
  );
}
